# Generated by Django 5.2.11 on 2026-02-04 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("llm_analysis", "0002_default_data"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="promptauditlog",
            new_name="llm_analysi_user_id_5ede14_idx",
            old_name="llm_analysi_user_id_1d56e0_idx",
        ),
        migrations.RenameIndex(
            model_name="promptauditlog",
            new_name="llm_analysi_was_fil_1ca5cb_idx",
            old_name="llm_analysi_was_fil_dc61a9_idx",
        ),
    ]
